version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - /usr/src/my-app/front/node_modules
      - .:/usr/src/my-app/front
    command: ["npm", "run", "dev"]
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/my-app/front/node_modules
      - .:/usr/src/my-app/front
    command: ["npm", "run", "test"]